Switch to parallel build/artifacts in circleci
drud/quicksprint pull request #85
Opened 2018-08-22 14:07 UTC by rfay

Just learned how to parallelize the test and artifacts creation in circleci, so doing that here. Sometimes you just don't want to wait for the tests to complete to work with the artifacts.

2018-08-22 14:22 UTC, mradcliffe requested changes
https://github.com/drud/quicksprint/blob/master/tests/test_drupal_quicksprint.sh#L36

I think this needs to be changed to use `/tmp/drupal_sprint_package` rather than the tarball since it might not exist yet, and not cleanup that directory in the test run.

2018-08-22 15:19 UTC, rfay commented
I didn't quite understand what @mradcliffe - When this starts working the package/build happens before the test and before the artifact creation. So that should work shouldn't it?

2018-08-22 20:04 UTC, rfay commented
You can see and look at the *workflow* builds for this in https://circleci.com/gh/drud/workflows/quicksprint/tree/pull%2F85

<img width="706" alt="circleci_-_circleci" src="https://user-images.githubusercontent.com/112444/44487754-4d39f200-a614-11e8-9608-afcfd0d81e62.png">

2018-08-23 13:19 UTC, mradcliffe approved these changes

2018-08-23 14:02 UTC, merged